"""依 team.yaml 動態產出 .env.example。

Usage:
    python gen_env.py [path/to/team.yaml] [output_path]

根據 team.yaml 的 channel 設定和 instances 動態決定需要哪些環境變數。
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml


def gen_env(team_path: Path) -> str:
    """產出 .env.example 內容。"""
    with open(team_path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    lines: list[str] = [
        "# .env.example",
        "# Auto-generated by ark-agent-team-init",
        "# Copy to .env and fill in actual values",
        "",
    ]

    # Telegram token
    channel = cfg.get("channel", {}) or {}
    token_env = channel.get("bot_token_env", "TELEGRAM_BOT_TOKEN")
    lines.append(f"# Telegram Bot")
    lines.append(f"{token_env}=your-token-here")
    lines.append("")

    # Check if any instance might need Gemini
    instances = cfg.get("instances", {})
    has_analyst = any("analyst" in n for n in instances)

    lines.append("# LLM API Keys (optional)")
    lines.append("# GEMINI_API_KEY=your-key-here")
    lines.append("# OPENAI_API_KEY=your-key-here")
    lines.append("")

    # Database (if analyst exists)
    if has_analyst:
        lines.append("# Database (for analyst)")
        lines.append("# DATABASE_URL=postgresql://user:pass@localhost/db")
        lines.append("# BIGQUERY_PROJECT=your-project-id")
        lines.append("")

    # Team agent home
    lines.append("# Team Agent")
    lines.append("# ARK_TEAM_AGENT_HOME=/path/to/team-home")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    team_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("team.yaml")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(".env.example")

    if not team_path.exists():
        print(f"❌ {team_path} not found")
        sys.exit(1)

    content = gen_env(team_path)
    out_path.write_text(content, encoding="utf-8")
    print(f"✅ Written {out_path}")


if __name__ == "__main__":
    main()
