"""Generator: Docker files."""
from pathlib import Path

DOCKERFILE = 'FROM python:3.12-slim\n\nWORKDIR /app\n\n# System deps\nRUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*\n\n# Python deps\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\n# App code\nCOPY src/ src/\nCOPY start_platform.py .\nCOPY team.yaml .\nCOPY scheduler.yaml .\n\n# Create dirs\nRUN mkdir -p data logs agents\n\nEXPOSE 33333\n\nCMD ["python", "start_platform.py"]\n'

COMPOSE = 'version: "3.9"\n\nservices:\n  postgres:\n    image: postgres:17-alpine\n    environment:\n      POSTGRES_DB: ark_platform\n      POSTGRES_USER: ark\n      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ark_secret}\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    ports:\n      - "5432:5432"\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U ark"]\n      interval: 5s\n      timeout: 3s\n      retries: 5\n\n  backend:\n    build:\n      context: .\n      dockerfile: Dockerfile\n    command: python -m uvicorn backend.api.router:app --host 0.0.0.0 --port 33333\n    environment:\n      - DATABASE_URL=postgresql://ark:${POSTGRES_PASSWORD:-ark_secret}@postgres:5432/ark_platform\n      - PLATFORM_API_KEYS=${PLATFORM_API_KEYS:-}\n      - API_PORT=33333\n    ports:\n      - "33333:33333"\n    depends_on:\n      postgres:\n        condition: service_healthy\n    working_dir: /app\n    volumes:\n      - ./data:/app/data\n      - ./logs:/app/logs\n\n  telegram-bot:\n    build:\n      context: .\n      dockerfile: Dockerfile\n    command: python start_platform.py\n    environment:\n      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}\n      - API_PORT=33333\n      - PLATFORM_API_KEYS=${PLATFORM_API_KEYS:-}\n    depends_on:\n      - backend\n    working_dir: /app\n    volumes:\n      - ./agents:/app/agents\n      - ./team.yaml:/app/team.yaml\n      - ./scheduler.yaml:/app/scheduler.yaml\n      - ./data:/app/data\n      - ./logs:/app/logs\n\n  agent-daemon:\n    build:\n      context: .\n      dockerfile: Dockerfile\n    command: python -c "import asyncio; from ark_team_core.daemon import CoreDaemon; d=CoreDaemon(); asyncio.run(d.run())"\n    environment:\n      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}\n    depends_on:\n      - backend\n    working_dir: /app\n    volumes:\n      - ./agents:/app/agents\n      - ./team.yaml:/app/team.yaml\n      - ./logs:/app/logs\n\nvolumes:\n  pgdata:\n'


def write_docker(output_dir: Path) -> None:
    (output_dir / "Dockerfile").write_text(DOCKERFILE, encoding="utf-8")
    (output_dir / "docker-compose.prod.yml").write_text(COMPOSE, encoding="utf-8")
